extends Node

signal addXP
signal chargeTrigger
signal damageAppliedAt
signal fireDwarfAxeProjectile
signal fireThiefKnifeProjectile
signal fireWizardSpellProjectile
signal fireElfArrowProjectile
signal monsterWasKilled
signal playerAnimationFinished
signal playerPressedAttack
signal shakeScreen
signal tailBombDrop
signal transitionToRoom





