extends Node

signal chargeTrigger
signal playerAnimationFinished
signal shakeScreen
signal tailBombDrop
signal transitionToRoom
signal monsterWasKilled
signal damageAppliedAt
signal playerPressedAttack
signal fireDwarfAxeProjectile
signal fireThiefKnifeProjectile
signal fireWizardSpellProjectile
