extends Node

enum GAME_STATE { IDLE, AWAIT_INPUT }
enum PLAYER_STATE { IDLE, AIR, WALKING, FALLING, JUMPING }
enum TAIL_TYPE { NONE, FIGHER, WIZARD }
enum ROOMS {
	NONE
	PLAINS_START,
	PLAINS_VILLAGE,
	PLAINS_WEST
}
enum DIRECTIONS { RIGHT, UP, LEFT, DOWN }

var HORI_SPEED = 130
var HORI_STOP = 0.4
var GRAVITY = 20
var JUMP_STRENGTH = -400

var CURRENT_ROOM = ROOMS.PLAINS_START
var PREVIOUS_ROOM = ROOMS.NONE

var TAIL_SIZE = 18
var X_POSITIONS = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
var Y_POSITIONS = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
var TAIL_ANIMATION = [
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE
]
var TAIL_DIRECTION = [
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT,
	DIRECTIONS.RIGHT
]

var playerState = PLAYER_STATE.IDLE
var gameState = GAME_STATE.IDLE

var items = [ null, null, null, null, null, null, null, null, null, null ]


var data = {
	"lv":1,
	"hp":0,
	"mp":0,
	"room": {
		"current": ROOMS.NONE,
		"x":0,
		"y":0
	},
	"tail1": {
		"type": TAIL_TYPE.NONE
	},
	"tail2": {
		"type": TAIL_TYPE.NONE
	},
	"tail3": {
		"type": TAIL_TYPE.NONE
	}
}
