extends Node

enum GAME_STATE { IDLE, AWAIT_INPUT }
enum PLAYER_STATE { IDLE, AIR, WALKING, FALLING, JUMPING }
enum TAIL_TYPE { NONE, POOCH, WIZARD, ELF, THIEF, CLERIC, DWARF }
enum ROOMS {
	NONE
	PLAINS_START,
	PLAINS_VILLAGE,
	PLAINS_WEST
}
enum DIRECTIONS { RIGHT, UP, LEFT, DOWN }

var STORAGE_PATH = "user://data/data.json"
var HORI_SPEED = 130
var HORI_STOP = 0.4
var GRAVITY = 20
var JUMP_STRENGTH = -400

var SCREEN_SIZE_X = 352
var SCREEN_SIZE_Y = 256


var CURRENT_ROOM = ROOMS.PLAINS_START
var PREVIOUS_ROOM = ROOMS.NONE
var ROOM_X = 0
var ROOM_Y = 0

var TAIL_SIZE = 18
var X_POSITIONS = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
var Y_POSITIONS = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
var TAIL_ANIMATION = [
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE,
	PLAYER_STATE.IDLE
]
var TAIL_DIRECTION = [
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false,
	false
]

var playerState = PLAYER_STATE.IDLE
var gameState = GAME_STATE.IDLE
var mapOffestX = 0
var mapOffsetY = 0


